application: canoe09
version: 3
runtime: python
api_version: 1

default_expiration: '3650d'

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  mime_type: image
  
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /css
  static_dir: media/css
  
- url: /images
  static_dir: media/images
  
- url: /resources
  static_dir: media/iphone/resources
  
- url: /lib
  static_dir: media/iphone/lib

- url: /js
  static_dir: media/js

- url: /media
  static_dir: _generated_media

- url: /.*
  script: common/appenginepatch/main.py
  

  
